spring:
  port: 8083
  cloud:
    gateway:
      routes:
        - id: account-management
          uri: lb://account-management
          predicates:
            - Path=/account-management/**
          filters:
            - StripPrefix=1
        - id: customer-management
          uri: lb://customer-management
          predicates:
            - Path=/customer-management/**
          filters:
            - StripPrefix=1
  application:
    name: gateway-rishi
